# Generated by Django 3.1.6 on 2021-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210219_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='TimeCreated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='TimeModified',
            field=models.DateField(auto_now=True),
        ),
    ]
