# Generated by Django 3.1.6 on 2021-02-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210219_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='TimeCreated',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='TimeModified',
            field=models.TimeField(auto_now=True),
        ),
    ]
